### PR TITLE
Fix check of enabled flag for add_deployment operation

### LINKED ISSUE #86: Add deployment operation always sets enabled to true
When adding a deployment it is always set to be enabled, even if the enabled field is set to false.

### PR DESCRIPTION
**Pull request by ammendonca**
The enabled flag was being set with `hash[:enabled] ||= true` which, if enabled
would be defined and set to false, it would evaluate as false and set it to true.

This checks if it is defined and only if it is not, it sets the default to true.

Fixes #86

### CODE REVIEW

File: lib/hawkular/operations/operations_api.rb [hunk 1]
```diff
@@ -134,7 +134,7 @@ def invoke_specific_operation(operation_payload, operation_name, &callback)
     #
     # @param callback [Block] callback that is run after the operation is done
     def add_deployment(hash, &callback)
-      hash[:enabled] ||= true
+      hash[:enabled] = defined?(hash[:enabled]) ? hash[:enabled] : true
```
Comment (abonas) [inline lib/hawkular/operations/operations_api.rb]: not sure what does the `defined?` return in this case, but why not using `hash[:enabled].key?`

Comment (ammendonca) [inline lib/hawkular/operations/operations_api.rb]: The result is the same, but indeed it seems more adequate to use the specific hash method `key?` instead of the generic `defined?`. Will change.

**Comment by pilhuhn** [comment]
I wonder if this enabled/disabled should also be checked in 'Operations/Add deployment should be doable' ?
